name: EAS Trigger - Deploy to production

on:
  push:
    branches: ['master']

jobs:
  fingerprint:
    name: Fingerprint
    type: fingerprint
    environment: production

  build_android:
    name: Build Android
    type: build
    needs: [get_android_build]
    params:
      platform: android
      profile: production
