name: Create development builds

jobs:
  android_development_build:
    name: Build Android
    type: build
    work-directory: ./frontend
    params:
      platform: android
      profile: development
